---
version: "3.9"

name: tubestats

services:
  app:
    container_name: tubestats
    image: tubestats:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT:-8003}:8000
    restart: unless-stopped
    volumes:
      - ./src/:/code/src/
      - ./tests/:/code/tests/
    expose:
      - 8000
